/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author stoker
 */
public class CheckDistancesGUI extends javax.swing.JFrame {

    /**
     * Creates new form A11GUIAPP
     */
    public CheckDistancesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Seattle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("San Francisco");

        jButton3.setText("Los Angeles");

        jButton4.setText("Las Vegas");

        jButton5.setText("Phoenix");

        jButton6.setText("Oklahoma City");

        jButton7.setText("Dallas");

        jButton8.setText("Minneapolis");

        jButton9.setText("Milwaukee");

        jButton10.setText("Chicago");

        jButton11.setText("Seattle");

        jButton12.setText("San Francisco");

        jButton13.setText("Los Angeles");

        jButton14.setText("Las Vegas");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Phoenix");

        jButton16.setText("Oklahoma City");

        jButton17.setText("Dallas");

        jButton18.setText("Minneapolis");

        jButton19.setText("Milwaukee");

        jButton20.setText("Chicago");

        jTextField1.setText("Check Distances App");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton21.setText("New Orleans");

        jButton22.setText("New York City");

        jButton23.setText("Washington DC");

        jButton24.setText("Miami");

        jButton25.setText("New Orleans");

        jButton26.setText("New York City");

        jButton27.setText("Washington DC");

        jButton28.setText("Miami");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(75, 75, 75)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton27)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton15)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21)
                    .addComponent(jButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton22)
                    .addComponent(jButton26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton23)
                    .addComponent(jButton27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton24)
                    .addComponent(jButton28))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckDistancesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckDistancesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckDistancesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckDistancesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckDistancesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}


/*
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

  
import javax.swing.GroupLayout;

import javax.swing.JFrame;

import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

import javax.swing.GroupLayout.Alignment;


@SuppressWarnings("serial")
public class CheckDistancesGUI extends JFrame implements ActionListener{
		private JRadioButton sea, sfr, la, lv, pho, okc,
				dal, min, mil, chi, nor, nyc, wdc, mia;
		JTextArea output;
		private JPanel jPanelFrom, jPanelTo;

        
		public CheckDistancesGUI()
		{
			guiComponents();
		}
	
		private void guiComponents() {
			  
	        jPanelFrom = new JPanel();
	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setBackground(new java.awt.Color(139, 0, 0));
	        
	        output = new JTextArea();
	        output.setText("Check the distance");
	        
	        sea = new JRadioButton();
	        sea.setText("Seattle");
	        sea.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        sfr = new JRadioButton();
	        sfr.setText("San Francisco");
	        sfr.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        la = new JRadioButton();
	        la.setText("Los Angeles");
	        la.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        lv = new JRadioButton();
	        lv.setText("Las Vegas");
	        lv.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        pho = new JRadioButton();
	        pho.setText("Phoenix");
	        pho.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        okc = new JRadioButton();
	        okc.setText("Oklahoma City");
	        okc.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        dal = new JRadioButton();
	        dal.setText("Dallas");
	        dal.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        min = new JRadioButton();
	        min.setText("Minneapolis");
	        min.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        mil = new JRadioButton();
	        mil.setText("Milwaukee");
	        mil.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        chi = new JRadioButton();
	        chi.setText("Chicago");
	        chi.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        nor = new JRadioButton();
	        nor.setText("New Orleans");
	        nor.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        nyc = new JRadioButton();
	        nyc.setText("New York City");
	       
	        nyc.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        wdc = new JRadioButton();
	        wdc.setText("Washington DC");
	        
	        wdc.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        mia = new JRadioButton();
	        mia.setText("Miami");
	        mia.addActionListener(new java.awt.event.ActionListener()
	        {
	        	public void actionPerformed(ActionEvent e)
	        	{
	        		
	        	}
	        });
	        
	       
	        GroupLayout jPanelLayoutFrom = new GroupLayout(jPanelFrom);
	        jPanelLayoutFrom.setHorizontalGroup(
	        		jPanelLayoutFrom.createParallelGroup(Alignment.LEADING)
	        		.addGroup(jPanelLayoutFrom.createSequentialGroup()
	        				.addComponent(sea, 300, 300, 300)
	        				.addComponent(sfr, 300, 300, 300)
	        				.addComponent(la, 300, 300, 300)
	        				.addComponent(lv, 300, 300, 300)
	        				.addComponent(pho, 300, 300, 300)
	        				.addComponent(okc, 300, 300, 300)
	        				.addComponent(dal, 300, 300, 300)
	        				.addComponent(min, 300, 300, 300)
	        				.addComponent(mil, 300, 300, 300)
	        				.addComponent(chi, 300, 300, 300)
	        				.addComponent(nor, 300, 300, 300)
	        				.addComponent(nyc, 300, 300, 300)
	        				.addComponent(wdc, 300, 300, 300)
	        				.addComponent(mia, 300, 300, 300)
	        				.addGroup(jPanelLayoutFrom.createSequentialGroup()
	        						.addComponent(output, 300, 300, 300))
	        				)
	        		);
	       /* GroupLayout jPanelLayoutTo = new GroupLayout(jPanelTo);
	        jPanelLayoutFrom.setVerticalGroup(
	        		jPanelLayoutFrom.createParallelGroup(Alignment.LEADING)
	        		.addGroup(jPanelLayoutFrom.createSequentialGroup()
	        				.addComponent(sea)
	        				.addComponent(sfr)
	        				.addComponent(la)
	        				.addComponent(lv)
	        				.addComponent(pho)
	        				.addComponent(okc)
	        				.addComponent(dal)
	        				.addComponent(min)
	        				.addComponent(mil)
	        				.addComponent(chi)
	        				.addComponent(nor)
	        				.addComponent(nyc)
	        				.addComponent(wdc)
	        				.addComponent(mia)
	        				)
	        		);*/
	      /*  jPanelFrom.setLayout(jPanelLayoutFrom);
	        //jPanelTo.setLayout(jPanelLayoutTo);
	        
	        GroupLayout layoutFrom = new GroupLayout(getContentPane());
	        getContentPane().setLayout(layoutFrom);
	        layoutFrom.setHorizontalGroup(
	        		layoutFrom.createParallelGroup(GroupLayout.Alignment.LEADING)
	            .addGroup(GroupLayout.Alignment.TRAILING, layoutFrom.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jPanelFrom, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addContainerGap())
	        );
	        layoutFrom.setVerticalGroup(
	        		layoutFrom.createParallelGroup(GroupLayout.Alignment.LEADING)
	            .addGroup(layoutFrom.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jPanelFrom, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addContainerGap())
	        );*/
	       /* GroupLayout layoutTo = new GroupLayout(getContentPane());
	        getContentPane().setLayout(layoutTo);
	        layoutTo.setHorizontalGroup(
	        		layoutTo.createParallelGroup(GroupLayout.Alignment.LEADING)
	            .addGroup(GroupLayout.Alignment.TRAILING, layoutTo.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jPanelTo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addContainerGap())
	        );
	        layoutTo.setVerticalGroup(
	        		layoutTo.createParallelGroup(GroupLayout.Alignment.LEADING)
	            .addGroup(layoutTo.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jPanelTo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addContainerGap())
	        );*/
	        //pack();
/*		}
		

		@Override
		public void actionPerformed(ActionEvent arg0) {
			
		}
}
*/